# Generated by Django 2.0 on 2017-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes_total',
            field=models.FloatField(default=0),
        ),
    ]
